# Generated by Django 3.0.5 on 2020-05-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
