# Generated by Django 3.0.6 on 2020-06-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0002_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
