# Generated by Django 3.0.5 on 2020-05-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0003_itemvariation_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
