# Generated by Django 3.0.5 on 2020-04-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0005_auto_20200418_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.DecimalField(decimal_places=3, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ManyToManyField(related_name='carts', to='Ecommerce.Product'),
        ),
    ]
