# Generated by Django 3.0.5 on 2020-04-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0008_auto_20200419_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ManyToManyField(to='Ecommerce.Product'),
        ),
    ]
