# Generated by Django 3.0.5 on 2020-05-06 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0009_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.Product'),
            preserve_default=False,
        ),
    ]
