# Generated by Django 3.0.5 on 2020-04-21 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0011_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orderid',
            new_name='order_id',
        ),
    ]
