# Generated by Django 3.0.5 on 2020-04-21 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0012_auto_20200422_0143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='number',
        ),
    ]
